### ISSUE TITLE
rails g foundation:install doesn't work because it expects .coffee file

### ISSUE THREAD

**Issue by kurko** [zurb/foundation-rails#197]
On Rails `4.2.7`, foundation-rails `6.2.3.0`,

```
→ be rails g foundation:install
      insert  app/assets/javascripts/application.coffee
/Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/kurko/www/adhoc/app/assets/javascripts/application.coffee (Errno::ENOENT)
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/foundation-rails-6.2.3.0/lib/generators/foundation/install_generator.rb:16:in `add_assets'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.7/lib/rails/generators.rb:157:in `invoke'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.7/lib/rails/commands/generate.rb:13:in `<top (required)>'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/kurko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

I don't use any Coffeescript. Is there a command I can fix this without going into the code myself and changing it?

Thanks

**Comment by kurko** [comment]
So, I don't have any file in `app/assets/{javascript,stylesheets}/`, I have folder for different app areas. I created a file there and it worked.

**Comment by keilmillerjr** [comment]
Rails no longer ships with coffeescript. Should consider requiring the gem, or removing the dependency on it.
