### ISSUE TITLE
Does't work with jruby

### ISSUE THREAD

**Issue by simonykq** [zurb/foundation-rails#204]
Hi,

I am using jRuby on Rails with the *therubyrhino* as the execjs runtime. But the javascripts assets within *foundation-rails* doesn't seem to compile when I run **rake assets:precompile**. See following stacktrace:

```ruby
ExecJS::ProgramError: 
at (execjs):54362
at (execjs):54297 (toType)
at (execjs):54328
at (execjs):51195
at (execjs):2 (s)
at (execjs):2
at (execjs):54991
at (execjs):2 (s)
at (execjs):2
at (execjs):50819
at (execjs):2 (s)
at (execjs):2
at (execjs):50975
at (execjs):50974
at (execjs):2 (s)
at (execjs):2
at (execjs):43642
at (execjs):2 (s)
at (execjs):2
at (execjs):44050
at (execjs):44035
at (execjs):2 (s)
at (execjs):2
at (execjs):20165
at (execjs):2 (s)
at (execjs):2
at (execjs):19106
at (execjs):2 (s)
at (execjs):2
at (execjs):11412
at (execjs):2 (s)
at (execjs):2
at (execjs):3299
at (execjs):2 (s)
at (execjs):2
at (execjs):3145
at (execjs):3140
at (execjs):2 (s)
at (execjs):2 (e)
at (execjs):2
at (execjs):2
at (execjs):2
/home/syu/.rvm/gems/jruby-1.7.23/gems/therubyrhino-2.0.4/lib/rhino/context.rb:259:in `open'
/home/syu/.rvm/gems/jruby-1.7.23/gems/therubyrhino-2.0.4/lib/rhino/context.rb:140:in `eval'
/home/syu/.rvm/gems/jruby-1.7.23/gems/execjs-2.7.0/lib/execjs/ruby_rhino_runtime.rb:11:in `initialize'
/home/syu/.rvm/gems/jruby-1.7.23/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
/home/syu/.rvm/gems/jruby-1.7.23/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
/home/syu/.rvm/gems/jruby-1.7.23/gems/babel-transpiler-0.7.0/lib/babel/transpiler.rb:24:in `context'
/home/syu/.rvm/gems/jruby-1.7.23/gems/babel-transpiler-0.7.0/lib/babel/transpiler.rb:28:in `transform'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-es6-0.9.2/lib/sprockets/es6.rb:70:in `transform'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-es6-0.9.2/lib/sprockets/es6.rb:64:in `call'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/cache.rb:85:in `fetch'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-es6-0.9.2/lib/sprockets/es6.rb:63:in `call'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-es6-0.9.2/lib/sprockets/es6.rb:34:in `call'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `call_processors'
org/jruby/RubyArray.java:1693:in `reverse_each'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `load'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `initialize'
org/jruby/RubyProc.java:281:in `call'
org/jruby/RubyHash.java:708:in `default'
org/jruby/RubyHash.java:1093:in `[]'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:23:in `call'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/utils.rb:196:in `dfs'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:24:in `call'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `call_processors'
org/jruby/RubyArray.java:1693:in `reverse_each'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `load'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `initialize'
org/jruby/RubyProc.java:281:in `call'
org/jruby/RubyHash.java:708:in `default'
org/jruby/RubyHash.java:1093:in `[]'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:142:in `find'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:114:in `logical_paths'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:228:in `stat_tree'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:212:in `stat_directory'
org/jruby/RubyArray.java:1613:in `each'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:227:in `stat_tree'
org/jruby/RubyEnumerator.java:274:in `each'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:105:in `logical_paths'
org/jruby/RubyArray.java:1613:in `each'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:104:in `logical_paths'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:140:in `find'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:185:in `compile'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `define'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-3.7.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/syu/.rvm/gems/jruby-1.7.23/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `define'
org/jruby/RubyProc.java:281:in `call'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/task.rb:248:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/syu/.rvm/rubies/jruby-1.7.23/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/application.rb:80:in `run'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/syu/.rvm/gems/jruby-1.7.23@global/gems/rake-11.3.0/exe/rake:27:in `(root)'
org/jruby/RubyKernel.java:1059:in `load'
/home/syu/.rvm/gems/jruby-1.7.23@global/bin/rake:23:in `(root)'
```

I dont really know what is happening but when I remove the line `//= require foundation` in **application.js**, the above error wont happen

* jRuby version: *1.7.23*
* Rails version: *4.2.7*
* therubyrhino: *2.0.4*
* foundation-rails version: *6.2.4.0*

Thanks for helps

**Comment by januszm** [comment]
It seems like you have a Javascript code that cannot be evaluated properly by your execjs interpreter: `therubyrhino` . Try changing the interpreter to something else or look for bugs in Javascript code @simonykq . If that's not 'your' Javascript code, then perhaps Foundation's JS cannot be properly interpreted by therubyrhino.

**Comment by ncoden** [comment]
No reply from @simonykq after 1+ year. Closing.
